import { and, desc, eq, isNull } from "drizzle-orm";
import { z } from "zod";
import { approvals, auditLogs, jobs, modelProviders, notifications, subscriptions, usageRecords, workspaces } from "../../drizzle/schema";
import { getDb } from "../db";
import { requireProjectAccess, requireWorkspaceAccess } from "../platform";
import { getPrivateWorkerReadiness } from "../workerReadiness";
import { protectedProcedure, router } from "../_core/trpc";
import { TRPCError } from "@trpc/server";

export const operationsRouter = router({
  notifications: router({
    list: protectedProcedure.input(z.object({ workspaceId: z.number().int().positive(), unreadOnly: z.boolean().default(false) })).query(async ({ ctx, input }) => { await requireWorkspaceAccess(ctx.user.id, input.workspaceId, "read"); const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database is unavailable." }); const filters = [eq(notifications.userId, ctx.user.id), eq(notifications.workspaceId, input.workspaceId)]; if (input.unreadOnly) filters.push(isNull(notifications.readAt)); return db.select().from(notifications).where(and(...filters)).orderBy(desc(notifications.createdAt)); }),
    markRead: protectedProcedure.input(z.object({ workspaceId: z.number().int().positive(), notificationId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { await requireWorkspaceAccess(ctx.user.id, input.workspaceId, "read"); const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database is unavailable." }); await db.update(notifications).set({ readAt: new Date() }).where(and(eq(notifications.id, input.notificationId), eq(notifications.userId, ctx.user.id), eq(notifications.workspaceId, input.workspaceId))); return { markedRead: true }; }),
  }),
  approvals: router({
    list: protectedProcedure.input(z.object({ workspaceId: z.number().int().positive(), status: z.enum(["pending", "approved", "rejected", "changes_requested"]).optional() })).query(async ({ ctx, input }) => { await requireWorkspaceAccess(ctx.user.id, input.workspaceId, "read"); const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database is unavailable." }); const filters = [eq(approvals.workspaceId, input.workspaceId)]; if (input.status) filters.push(eq(approvals.status, input.status)); return db.select().from(approvals).where(and(...filters)).orderBy(desc(approvals.createdAt)); }),
    resolve: protectedProcedure.input(z.object({ workspaceId: z.number().int().positive(), approvalId: z.number().int().positive(), status: z.enum(["approved", "rejected", "changes_requested"]), comment: z.string().max(2000).optional() })).mutation(async ({ ctx, input }) => { await requireWorkspaceAccess(ctx.user.id, input.workspaceId, "review"); const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database is unavailable." }); await db.update(approvals).set({ status: input.status, comment: input.comment ?? null, resolvedByUserId: ctx.user.id, updatedAt: new Date() }).where(and(eq(approvals.id, input.approvalId), eq(approvals.workspaceId, input.workspaceId))); return { resolved: true, status: input.status }; }),
  }),
  plan: protectedProcedure.input(z.object({ workspaceId: z.number().int().positive() })).query(async ({ ctx, input }) => { await requireWorkspaceAccess(ctx.user.id, input.workspaceId, "read"); const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database is unavailable." }); const workspace = (await db.select().from(workspaces).where(eq(workspaces.id, input.workspaceId)).limit(1))[0]; if (!workspace) throw new TRPCError({ code: "NOT_FOUND", message: "Workspace not found." }); const subscription = (await db.select().from(subscriptions).where(eq(subscriptions.organizationId, workspace.organizationId)).orderBy(desc(subscriptions.updatedAt)).limit(1))[0] ?? null; return subscription ? { plan: subscription.plan, status: subscription.status, providerReference: subscription.providerReference } : { plan: "free" as const, status: "active" as const, providerReference: null };
  }),
  usage: router({
    summary: protectedProcedure.input(z.object({ workspaceId: z.number().int().positive() })).query(async ({ ctx, input }) => { await requireWorkspaceAccess(ctx.user.id, input.workspaceId, "read"); const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database is unavailable." }); const rows = await db.select().from(usageRecords).where(eq(usageRecords.workspaceId, input.workspaceId)); const totals = rows.reduce<Record<string, number>>((acc, row) => { acc[row.metric] = (acc[row.metric] ?? 0) + row.quantity; return acc; }, {}); return { totals, records: rows.slice(0, 100) }; }),
  }),
  audit: protectedProcedure.input(z.object({ workspaceId: z.number().int().positive(), limit: z.number().int().min(1).max(100).default(50) })).query(async ({ ctx, input }) => { await requireWorkspaceAccess(ctx.user.id, input.workspaceId, "read"); const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database is unavailable." }); return db.select().from(auditLogs).where(eq(auditLogs.workspaceId, input.workspaceId)).orderBy(desc(auditLogs.createdAt)).limit(input.limit); }),
  health: protectedProcedure.query(async ({ ctx }) => { if (ctx.user.role !== "admin") throw new TRPCError({ code: "FORBIDDEN", message: "Administrator access is required." }); const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database is unavailable." }); const providers = await db.select().from(modelProviders); const failedJobs = await db.select().from(jobs).where(eq(jobs.status, "failed")); return { providers: { total: providers.length, enabled: providers.filter(item => item.enabled === "yes").length, unhealthy: providers.filter(item => item.healthStatus === "unhealthy").length }, privateWorkers: getPrivateWorkerReadiness(), failedJobs: failedJobs.length, checkedAt: new Date() }; }),
});
