import { index, int, json, mysqlEnum, mysqlTable, text, timestamp, varchar } from "drizzle-orm/mysql-core";

/**
 * Core user table backing auth flow.
 * Extend this file with additional tables as your product grows.
 * Columns use camelCase to match both database fields and generated types.
 */
export const users = mysqlTable("users", {
  /**
   * Surrogate primary key. Auto-incremented numeric value managed by the database.
   * Use this for relations between tables.
   */
  id: int("id").autoincrement().primaryKey(),
  /** Manus OAuth identifier (openId) returned from the OAuth callback. Unique per user. */
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

const createdAt = timestamp("createdAt").defaultNow().notNull();
const updatedAt = timestamp("updatedAt").defaultNow().onUpdateNow().notNull();

export const organizations = mysqlTable("organizations", {
  id: int("id").autoincrement().primaryKey(), name: varchar("name", { length: 160 }).notNull(), slug: varchar("slug", { length: 191 }).notNull().unique(), kind: mysqlEnum("kind", ["studio", "agency", "client"]).notNull(), ownerUserId: int("ownerUserId").notNull().references(() => users.id), createdAt, updatedAt,
});
export const workspaces = mysqlTable("workspaces", {
  id: int("id").autoincrement().primaryKey(), organizationId: int("organizationId").notNull().references(() => organizations.id), name: varchar("name", { length: 160 }).notNull(), slug: varchar("slug", { length: 191 }).notNull(), kind: mysqlEnum("kind", ["primary", "client", "sandbox"]).notNull().default("primary"), createdAt, updatedAt,
}, table => [index("workspaces_organization_idx").on(table.organizationId)]);
export const memberships = mysqlTable("memberships", {
  id: int("id").autoincrement().primaryKey(), userId: int("userId").notNull().references(() => users.id), organizationId: int("organizationId").notNull().references(() => organizations.id), workspaceId: int("workspaceId").notNull().references(() => workspaces.id), role: mysqlEnum("role", ["owner", "admin", "editor", "reviewer", "viewer", "client"]).notNull(), status: mysqlEnum("status", ["active", "invited", "suspended"]).notNull().default("active"), createdAt, updatedAt,
}, table => [index("memberships_user_workspace_idx").on(table.userId, table.workspaceId), index("memberships_workspace_idx").on(table.workspaceId)]);

export const projects = mysqlTable("projects", {
  id: int("id").autoincrement().primaryKey(), workspaceId: int("workspaceId").notNull().references(() => workspaces.id), title: varchar("title", { length: 180 }).notNull(), description: text("description"), status: mysqlEnum("status", ["idea", "scripting", "generating", "editing", "ready", "scheduled", "published", "failed", "archived"]).notNull().default("idea"), createdByUserId: int("createdByUserId").notNull().references(() => users.id), createdAt, updatedAt,
}, table => [index("projects_workspace_idx").on(table.workspaceId)]);
export const videos = mysqlTable("videos", {
  id: int("id").autoincrement().primaryKey(), projectId: int("projectId").notNull().references(() => projects.id), title: varchar("title", { length: 180 }).notNull(), status: mysqlEnum("status", ["idea", "scripting", "generating", "editing", "ready", "scheduled", "published", "failed", "archived"]).notNull().default("idea"), aspectRatio: varchar("aspectRatio", { length: 16 }).notNull().default("16:9"), createdByUserId: int("createdByUserId").notNull().references(() => users.id), createdAt, updatedAt,
}, table => [index("videos_project_idx").on(table.projectId)]);
export const videoVersions = mysqlTable("videoVersions", {
  id: int("id").autoincrement().primaryKey(), videoId: int("videoId").notNull().references(() => videos.id), versionNumber: int("versionNumber").notNull(), label: varchar("label", { length: 160 }).notNull(), projectDocument: json("projectDocument").notNull(), exportUrl: text("exportUrl"), qualityScore: int("qualityScore"), createdByUserId: int("createdByUserId").notNull().references(() => users.id), createdAt,
}, table => [index("video_versions_video_idx").on(table.videoId)]);
export const scripts = mysqlTable("scripts", {
  id: int("id").autoincrement().primaryKey(), projectId: int("projectId").notNull().references(() => projects.id), videoId: int("videoId").references(() => videos.id), language: varchar("language", { length: 12 }).notNull(), content: json("content").notNull(), createdByUserId: int("createdByUserId").notNull().references(() => users.id), updatedByUserId: int("updatedByUserId").notNull().references(() => users.id), createdAt, updatedAt,
}, table => [index("scripts_project_idx").on(table.projectId)]);
export const scenes = mysqlTable("scenes", { id: int("id").autoincrement().primaryKey(), videoVersionId: int("videoVersionId").notNull().references(() => videoVersions.id), sceneKey: varchar("sceneKey", { length: 64 }).notNull(), position: int("position").notNull(), content: json("content").notNull(), createdAt, updatedAt }, table => [index("scenes_version_idx").on(table.videoVersionId)]);
export const tracks = mysqlTable("tracks", { id: int("id").autoincrement().primaryKey(), videoVersionId: int("videoVersionId").notNull().references(() => videoVersions.id), type: mysqlEnum("type", ["video", "scene", "audio", "broll", "voice", "music", "sfx", "captions", "overlay"]).notNull(), position: int("position").notNull(), configuration: json("configuration").notNull(), createdAt, updatedAt }, table => [index("tracks_version_idx").on(table.videoVersionId)]);

export const folders = mysqlTable("folders", { id: int("id").autoincrement().primaryKey(), workspaceId: int("workspaceId").notNull().references(() => workspaces.id), parentId: int("parentId"), name: varchar("name", { length: 160 }).notNull(), createdByUserId: int("createdByUserId").notNull().references(() => users.id), createdAt, updatedAt }, table => [index("folders_workspace_idx").on(table.workspaceId)]);
export const assets = mysqlTable("assets", {
  id: int("id").autoincrement().primaryKey(), workspaceId: int("workspaceId").notNull().references(() => workspaces.id), projectId: int("projectId").references(() => projects.id), folderId: int("folderId").references(() => folders.id), type: mysqlEnum("type", ["video", "image", "audio", "music", "sfx", "font", "thumbnail", "caption", "document"]).notNull(), title: varchar("title", { length: 180 }).notNull(), storageKey: text("storageKey"), storageUrl: text("storageUrl"), source: mysqlEnum("source", ["upload", "ai_generated", "stock", "user_provided", "derived"]).notNull(), rightsStatus: mysqlEnum("rightsStatus", ["verified", "review_required", "attribution_required", "restricted", "unknown"]).notNull().default("unknown"), license: varchar("license", { length: 240 }), author: varchar("author", { length: 240 }), attribution: text("attribution"), tags: json("tags"), metadata: json("metadata"), createdByUserId: int("createdByUserId").notNull().references(() => users.id), createdAt, updatedAt,
}, table => [index("assets_workspace_type_idx").on(table.workspaceId, table.type), index("assets_project_idx").on(table.projectId)]);
export const voices = mysqlTable("voices", { id: int("id").autoincrement().primaryKey(), workspaceId: int("workspaceId").notNull().references(() => workspaces.id), name: varchar("name", { length: 160 }).notNull(), provider: varchar("provider", { length: 100 }).notNull(), providerVoiceId: varchar("providerVoiceId", { length: 191 }).notNull(), language: varchar("language", { length: 16 }).notNull(), gender: mysqlEnum("gender", ["male", "female", "neutral"]).notNull().default("neutral"), tone: varchar("tone", { length: 80 }), accent: varchar("accent", { length: 80 }), speed: varchar("speed", { length: 32 }), emotion: varchar("emotion", { length: 80 }), commercialUse: mysqlEnum("commercialUse", ["allowed", "review", "restricted"]).notNull().default("review"), createdAt, updatedAt }, table => [index("voices_workspace_idx").on(table.workspaceId)]);
export const voiceConsents = mysqlTable("voiceConsents", { id: int("id").autoincrement().primaryKey(), voiceId: int("voiceId").notNull().references(() => voices.id), workspaceId: int("workspaceId").notNull().references(() => workspaces.id), status: mysqlEnum("status", ["pending", "verified", "revoked"]).notNull().default("pending"), approvedUseScope: mysqlEnum("approvedUseScope", ["commercial_tts", "internal_only"]).notNull().default("internal_only"), evidenceReference: varchar("evidenceReference", { length: 500 }), verifiedByUserId: int("verifiedByUserId").references(() => users.id), verifiedAt: timestamp("verifiedAt"), createdAt, updatedAt }, table => [index("voice_consents_voice_idx").on(table.voiceId), index("voice_consents_workspace_idx").on(table.workspaceId)]);
export const transcripts = mysqlTable("transcripts", { id: int("id").autoincrement().primaryKey(), projectId: int("projectId").notNull().references(() => projects.id), language: varchar("language", { length: 16 }).notNull(), text: text("text").notNull(), segments: json("segments"), sourceUrl: text("sourceUrl"), createdByUserId: int("createdByUserId").notNull().references(() => users.id), createdAt, updatedAt }, table => [index("transcripts_project_idx").on(table.projectId)]);
export const captions = mysqlTable("captions", { id: int("id").autoincrement().primaryKey(), projectId: int("projectId").notNull().references(() => projects.id), transcriptId: int("transcriptId").references(() => transcripts.id), language: varchar("language", { length: 16 }).notNull(), style: varchar("style", { length: 80 }).notNull(), srt: text("srt"), vtt: text("vtt"), wordTiming: json("wordTiming"), createdByUserId: int("createdByUserId").notNull().references(() => users.id), createdAt, updatedAt }, table => [index("captions_project_idx").on(table.projectId)]);

export const researchSources = mysqlTable("researchSources", { id: int("id").autoincrement().primaryKey(), projectId: int("projectId").notNull().references(() => projects.id), title: varchar("title", { length: 300 }).notNull(), url: text("url"), excerpt: text("excerpt").notNull(), sourceType: mysqlEnum("sourceType", ["user_provided", "verified", "ai_generated"]).notNull().default("user_provided"), createdByUserId: int("createdByUserId").notNull().references(() => users.id), createdAt }, table => [index("research_sources_project_idx").on(table.projectId)]);
export const researchClaims = mysqlTable("researchClaims", { id: int("id").autoincrement().primaryKey(), projectId: int("projectId").notNull().references(() => projects.id), sourceId: int("sourceId").references(() => researchSources.id), text: text("text").notNull(), classification: mysqlEnum("classification", ["verified", "ai_generated", "user_provided"]).notNull(), confidence: varchar("confidence", { length: 16 }), createdByUserId: int("createdByUserId").notNull().references(() => users.id), createdAt }, table => [index("research_claims_project_idx").on(table.projectId)]);
export const researchCitations = mysqlTable("researchCitations", { id: int("id").autoincrement().primaryKey(), projectId: int("projectId").notNull().references(() => projects.id), claimId: int("claimId").references(() => researchClaims.id), sourceId: int("sourceId").notNull().references(() => researchSources.id), quote: text("quote").notNull(), locator: varchar("locator", { length: 240 }), verifiedByUserId: int("verifiedByUserId").references(() => users.id), createdAt }, table => [index("research_citations_project_idx").on(table.projectId), index("research_citations_claim_idx").on(table.claimId)]);
export const researchSummaries = mysqlTable("researchSummaries", { id: int("id").autoincrement().primaryKey(), projectId: int("projectId").notNull().references(() => projects.id), summary: text("summary").notNull(), sourceCount: int("sourceCount").notNull(), verifiedClaimCount: int("verifiedClaimCount").notNull(), synthesisClaimCount: int("synthesisClaimCount").notNull(), createdByUserId: int("createdByUserId").notNull().references(() => users.id), createdAt }, table => [index("research_summaries_project_idx").on(table.projectId)]);

export const jobs = mysqlTable("jobs", { id: int("id").autoincrement().primaryKey(), workspaceId: int("workspaceId").notNull().references(() => workspaces.id), projectId: int("projectId").references(() => projects.id), videoId: int("videoId").references(() => videos.id), type: mysqlEnum("type", ["script_generation", "research", "tts", "transcription", "image_generation", "video_generation", "video_render", "caption_generation", "short_detection", "short_render", "thumbnail_generation", "upload", "social_publish", "analytics_sync", "translation"]).notNull(), status: mysqlEnum("status", ["queued", "processing", "retrying", "completed", "failed", "cancelled"]).notNull().default("queued"), progress: int("progress").notNull().default(0), payload: json("payload"), result: json("result"), idempotencyKey: varchar("idempotencyKey", { length: 64 }).notNull().unique(), errorCode: varchar("errorCode", { length: 100 }), errorMessage: text("errorMessage"), retryCount: int("retryCount").notNull().default(0), cancelRequestedAt: timestamp("cancelRequestedAt"), startedAt: timestamp("startedAt"), completedAt: timestamp("completedAt"), createdByUserId: int("createdByUserId").notNull().references(() => users.id), createdAt, updatedAt }, table => [index("jobs_workspace_status_idx").on(table.workspaceId, table.status), index("jobs_project_idx").on(table.projectId)]);
export const jobEvents = mysqlTable("jobEvents", { id: int("id").autoincrement().primaryKey(), jobId: int("jobId").notNull().references(() => jobs.id), level: mysqlEnum("level", ["info", "warning", "error"]).notNull().default("info"), message: text("message").notNull(), progress: int("progress"), createdAt }, table => [index("job_events_job_idx").on(table.jobId)]);
export const copilotActions = mysqlTable("copilotActions", { id: int("id").autoincrement().primaryKey(), projectId: int("projectId").notNull().references(() => projects.id), workspaceId: int("workspaceId").notNull().references(() => workspaces.id), jobId: int("jobId").references(() => jobs.id), command: text("command").notNull(), toolName: varchar("toolName", { length: 120 }).notNull(), parameters: json("parameters").notNull(), executionStatus: mysqlEnum("executionStatus", ["queued", "running", "completed", "failed", "awaiting_approval", "cancelled"]).notNull(), createdByUserId: int("createdByUserId").notNull().references(() => users.id), createdAt, updatedAt }, table => [index("copilot_actions_project_idx").on(table.projectId)]);

export const socialAccounts = mysqlTable("socialAccounts", { id: int("id").autoincrement().primaryKey(), workspaceId: int("workspaceId").notNull().references(() => workspaces.id), platform: mysqlEnum("platform", ["youtube", "tiktok", "facebook", "instagram", "linkedin", "x"]).notNull(), accountName: varchar("accountName", { length: 160 }).notNull(), externalAccountId: varchar("externalAccountId", { length: 191 }), connectionStatus: mysqlEnum("connectionStatus", ["not_connected", "connected", "expired", "review_required", "error"]).notNull().default("not_connected"), encryptedTokenRef: text("encryptedTokenRef"), capabilities: json("capabilities"), createdAt, updatedAt }, table => [index("social_accounts_workspace_idx").on(table.workspaceId)]);
export const scheduledPosts = mysqlTable("scheduledPosts", { id: int("id").autoincrement().primaryKey(), workspaceId: int("workspaceId").notNull().references(() => workspaces.id), projectId: int("projectId").notNull().references(() => projects.id), socialAccountId: int("socialAccountId").references(() => socialAccounts.id), platform: mysqlEnum("platform", ["youtube", "tiktok", "facebook", "instagram", "linkedin", "x"]).notNull(), title: varchar("title", { length: 200 }), copy: text("copy"), status: mysqlEnum("status", ["draft", "awaiting_approval", "scheduled", "publishing", "published", "failed", "cancelled"]).notNull().default("draft"), scheduledFor: timestamp("scheduledFor"), scheduleCronTaskUid: varchar("scheduleCronTaskUid", { length: 65 }), createdByUserId: int("createdByUserId").notNull().references(() => users.id), createdAt, updatedAt }, table => [index("scheduled_posts_workspace_idx").on(table.workspaceId), index("scheduled_posts_task_uid_idx").on(table.scheduleCronTaskUid)]);
export const analyticsSnapshots = mysqlTable("analyticsSnapshots", { id: int("id").autoincrement().primaryKey(), workspaceId: int("workspaceId").notNull().references(() => workspaces.id), projectId: int("projectId").references(() => projects.id), platform: varchar("platform", { length: 32 }).notNull(), capturedAt: timestamp("capturedAt").notNull(), metrics: json("metrics").notNull(), provenance: mysqlEnum("provenance", ["official_api", "user_import", "unavailable"]).notNull(), createdAt }, table => [index("analytics_workspace_idx").on(table.workspaceId)]);
export const brandKits = mysqlTable("brandKits", { id: int("id").autoincrement().primaryKey(), workspaceId: int("workspaceId").notNull().references(() => workspaces.id), name: varchar("name", { length: 160 }).notNull(), configuration: json("configuration").notNull(), createdByUserId: int("createdByUserId").notNull().references(() => users.id), createdAt, updatedAt }, table => [index("brand_kits_workspace_idx").on(table.workspaceId)]);
export const templates = mysqlTable("templates", { id: int("id").autoincrement().primaryKey(), workspaceId: int("workspaceId").references(() => workspaces.id), name: varchar("name", { length: 160 }).notNull(), category: varchar("category", { length: 80 }).notNull(), configuration: json("configuration").notNull(), createdByUserId: int("createdByUserId").references(() => users.id), createdAt, updatedAt });
export const approvals = mysqlTable("approvals", { id: int("id").autoincrement().primaryKey(), workspaceId: int("workspaceId").notNull().references(() => workspaces.id), projectId: int("projectId").notNull().references(() => projects.id), entityType: varchar("entityType", { length: 80 }).notNull(), entityId: varchar("entityId", { length: 80 }).notNull(), status: mysqlEnum("status", ["pending", "approved", "rejected", "changes_requested"]).notNull().default("pending"), requestedByUserId: int("requestedByUserId").notNull().references(() => users.id), resolvedByUserId: int("resolvedByUserId").references(() => users.id), comment: text("comment"), createdAt, updatedAt }, table => [index("approvals_workspace_idx").on(table.workspaceId)]);
export const subscriptions = mysqlTable("subscriptions", { id: int("id").autoincrement().primaryKey(), organizationId: int("organizationId").notNull().references(() => organizations.id), plan: mysqlEnum("plan", ["free", "creator", "pro", "agency", "enterprise"]).notNull().default("free"), status: mysqlEnum("status", ["active", "trialing", "past_due", "cancelled"]).notNull().default("active"), providerReference: varchar("providerReference", { length: 191 }), createdAt, updatedAt });
export const usageRecords = mysqlTable("usageRecords", { id: int("id").autoincrement().primaryKey(), workspaceId: int("workspaceId").notNull().references(() => workspaces.id), metric: mysqlEnum("metric", ["gpu_seconds", "render_minutes", "generated_videos", "tts_characters", "transcription_minutes", "storage_bytes", "api_requests", "social_posts"]).notNull(), quantity: int("quantity").notNull(), referenceType: varchar("referenceType", { length: 80 }), referenceId: varchar("referenceId", { length: 80 }), createdAt }, table => [index("usage_workspace_metric_idx").on(table.workspaceId, table.metric)]);
export const apiKeys = mysqlTable("apiKeys", { id: int("id").autoincrement().primaryKey(), workspaceId: int("workspaceId").notNull().references(() => workspaces.id), name: varchar("name", { length: 160 }).notNull(), keyPrefix: varchar("keyPrefix", { length: 32 }).notNull(), keyHash: varchar("keyHash", { length: 255 }).notNull(), scopes: json("scopes").notNull(), lastUsedAt: timestamp("lastUsedAt"), createdByUserId: int("createdByUserId").notNull().references(() => users.id), createdAt, updatedAt });
export const webhooks = mysqlTable("webhooks", { id: int("id").autoincrement().primaryKey(), workspaceId: int("workspaceId").notNull().references(() => workspaces.id), url: text("url").notNull(), secretReference: varchar("secretReference", { length: 191 }).notNull(), eventTypes: json("eventTypes").notNull(), active: mysqlEnum("active", ["yes", "no"]).notNull().default("yes"), createdByUserId: int("createdByUserId").notNull().references(() => users.id), createdAt, updatedAt });
export const notifications = mysqlTable("notifications", { id: int("id").autoincrement().primaryKey(), userId: int("userId").notNull().references(() => users.id), workspaceId: int("workspaceId").references(() => workspaces.id), type: varchar("type", { length: 80 }).notNull(), title: varchar("title", { length: 200 }).notNull(), body: text("body"), readAt: timestamp("readAt"), createdAt });
export const modelProviders = mysqlTable("modelProviders", { id: int("id").autoincrement().primaryKey(), name: varchar("name", { length: 160 }).notNull(), provider: varchar("provider", { length: 100 }).notNull(), endpoint: text("endpoint").notNull(), modelId: varchar("modelId", { length: 191 }).notNull(), costTier: mysqlEnum("costTier", ["free", "paid", "metered"]).notNull().default("free"), selfHosted: mysqlEnum("selfHosted", ["yes", "no"]).notNull().default("yes"), license: varchar("license", { length: 500 }), commercialUse: mysqlEnum("commercialUse", ["allowed", "review", "restricted"]).notNull().default("review"), vramGb: int("vramGb"), capabilities: json("capabilities").notNull(), languages: json("languages").notNull(), credentialReference: varchar("credentialReference", { length: 191 }), healthStatus: mysqlEnum("healthStatus", ["unknown", "healthy", "unhealthy"]).notNull().default("unknown"), enabled: mysqlEnum("enabled", ["yes", "no"]).notNull().default("no"), configuredByUserId: int("configuredByUserId").notNull().references(() => users.id), createdAt, updatedAt }, table => [index("model_providers_enabled_idx").on(table.enabled)]);
export const auditLogs = mysqlTable("auditLogs", { id: int("id").autoincrement().primaryKey(), workspaceId: int("workspaceId").notNull().references(() => workspaces.id), userId: int("userId").notNull().references(() => users.id), action: varchar("action", { length: 120 }).notNull(), entityType: varchar("entityType", { length: 80 }).notNull(), entityId: varchar("entityId", { length: 80 }).notNull(), metadata: json("metadata"), createdAt }, table => [index("audit_workspace_idx").on(table.workspaceId)]);
