import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { PageHeader } from "@/components/PageHeader";
import { ProjectPicker } from "@/components/ProjectPicker";
import { useWorkspace } from "@/hooks/useWorkspace";
import { trpc } from "@/lib/trpc";
import { FolderOpen, ImagePlus, Loader2, Search, ShieldCheck, Sparkles } from "lucide-react";
import { ChangeEvent, FormEvent, useState } from "react";
import { toast } from "sonner";

export default function AssetLibrary() {
  const { activeWorkspaceId } = useWorkspace(); const [projectId, setProjectId] = useState<number | null>(null); const [type, setType] = useState<"image" | "video" | "audio" | "music" | "sfx" | "thumbnail" | undefined>(); const [prompt, setPrompt] = useState(""); const [assetTitle, setAssetTitle] = useState(""); const [usage, setUsage] = useState<"scene_visual" | "broll" | "thumbnail">("scene_visual"); const [query, setQuery] = useState(""); const [uploading, setUploading] = useState(false);
  const assets = trpc.production.assets.list.useQuery({ workspaceId: activeWorkspaceId ?? 0, type }, { enabled: Boolean(activeWorkspaceId) }); const createImage = trpc.production.assets.createImage.useMutation(); const upload = trpc.production.assets.upload.useMutation();
  const generate = async (event: FormEvent) => { event.preventDefault(); if (!projectId) return toast.error("Select a project to attach the visual to."); try { await createImage.mutateAsync({ projectId, prompt, title: assetTitle || "Generated visual", usage }); await assets.refetch(); setPrompt(""); setAssetTitle(""); toast.success("Visual generated and saved with rights review status."); } catch (error) { toast.error(error instanceof Error ? error.message : "Image generation failed."); } };
  const inferAssetType = (file: File): "video" | "image" | "audio" | "document" => file.type.startsWith("video/") ? "video" : file.type.startsWith("audio/") ? "audio" : file.type.startsWith("image/") ? "image" : "document";
  const uploadFile = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file || !activeWorkspaceId) return; if (file.size > 16 * 1024 * 1024) { toast.error("Uploads are limited to 16 MB."); event.target.value = ""; return; } setUploading(true); try { const base64 = await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onerror = () => reject(new Error("Could not read the selected file.")); reader.onload = () => resolve(String(reader.result).split(",")[1] ?? ""); reader.readAsDataURL(file); }); await upload.mutateAsync({ workspaceId: activeWorkspaceId, projectId: projectId ?? undefined, title: file.name.replace(/\.[^.]+$/, ""), fileName: file.name, contentType: file.type || "application/octet-stream", dataBase64: base64, type: inferAssetType(file) }); await assets.refetch(); toast.success("Asset uploaded and stored securely."); } catch (error) { toast.error(error instanceof Error ? error.message : "Upload failed."); } finally { setUploading(false); event.target.value = ""; } };
  const filtered = assets.data?.filter(asset => asset.title.toLowerCase().includes(query.toLowerCase())) ?? [];
  return <div className="min-h-full bg-[#0b1020]"><PageHeader eyebrow="Production assets" title="Media Library" description="A rights-aware home for your footage, graphics, audio, captions, thumbnails, and generated visual directions." />
    <div className="mx-auto grid max-w-[1600px] gap-6 p-5 lg:grid-cols-[340px_1fr] md:p-8"><aside className="space-y-4"><Card className="border-white/7 bg-white/[.035] shadow-none"><CardContent className="p-5"><div className="flex items-center gap-2 text-cyan-200"><Sparkles className="h-4 w-4" /><span className="text-xs font-semibold uppercase tracking-[.15em]">Create visual</span></div><div className="mt-4 rounded-xl border border-dashed border-white/15 bg-slate-950/30 p-3"><label className="flex cursor-pointer items-center justify-between gap-3"><span className="text-xs text-slate-400">Upload an asset to S3</span><span className="rounded bg-white/7 px-2 py-1 text-[10px] text-cyan-200">{uploading ? "Uploading…" : "Browse"}</span><input type="file" className="hidden" onChange={uploadFile} disabled={uploading} /></label></div><form onSubmit={generate} className="mt-5 space-y-4"><ProjectPicker projectId={projectId} onChange={setProjectId} /><label className="block"><span className="mb-1.5 block text-xs text-slate-400">Asset title</span><Input value={assetTitle} onChange={e => setAssetTitle(e.target.value)} placeholder="Cinematic security operations room" className="border-white/10 bg-slate-950/60 text-white placeholder:text-slate-600" /></label><label className="block"><span className="mb-1.5 block text-xs text-slate-400">Prompt</span><textarea required value={prompt} onChange={e => setPrompt(e.target.value)} placeholder="Describe a brand-consistent visual…" className="min-h-28 w-full rounded-lg border border-white/10 bg-slate-950/60 p-3 text-sm text-white outline-none placeholder:text-slate-600 focus:border-cyan-300/60" /></label><label className="block"><span className="mb-1.5 block text-xs text-slate-400">Intended use</span><select value={usage} onChange={e => setUsage(e.target.value as typeof usage)} className="h-10 w-full rounded-lg border border-white/10 bg-slate-950/60 px-3 text-sm text-white outline-none"><option value="scene_visual">Scene visual</option><option value="broll">B-roll visual</option><option value="thumbnail">Thumbnail concept</option></select></label><Button disabled={createImage.isPending || !projectId} className="w-full bg-cyan-300 text-slate-950 hover:bg-cyan-200">{createImage.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <ImagePlus className="mr-2 h-4 w-4" />}Generate and save</Button></form></CardContent></Card><div className="rounded-2xl border border-white/7 bg-white/[.02] p-4 text-xs leading-5 text-slate-500"><ShieldCheck className="mb-2 h-4 w-4 text-emerald-300" />Generated assets enter the library as <span className="font-medium text-slate-300">review required</span>. Add rights metadata before publishing.</div></aside>
      <main><Card className="border-white/7 bg-white/[.025] shadow-none"><CardContent className="p-0"><div className="flex flex-col gap-4 border-b border-white/7 p-5 md:flex-row md:items-center md:justify-between"><div><h2 className="font-medium text-white">Workspace assets</h2><p className="mt-1 text-xs text-slate-500">Search and filter all tracked media.</p></div><div className="flex gap-2"><div className="relative"><Search className="pointer-events-none absolute left-3 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-slate-600" /><Input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search assets" className="w-48 border-white/10 bg-slate-950/50 pl-8 text-white placeholder:text-slate-600" /></div><select value={type ?? ""} onChange={e => setType((e.target.value || undefined) as typeof type)} className="h-10 rounded-lg border border-white/10 bg-slate-950/60 px-3 text-xs text-slate-300 outline-none"><option value="">All media</option><option value="image">Images</option><option value="video">Video</option><option value="audio">Audio</option><option value="thumbnail">Thumbnails</option></select></div></div><div className="grid gap-4 p-5 sm:grid-cols-2 xl:grid-cols-3">{filtered.length ? filtered.map(asset => <article key={asset.id} className="overflow-hidden rounded-2xl border border-white/7 bg-slate-950/35"><div className="grid aspect-video place-items-center bg-gradient-to-br from-violet-400/15 via-slate-900 to-cyan-300/10">{asset.storageUrl ? <img src={asset.storageUrl} alt={asset.title} className="h-full w-full object-cover" /> : <FolderOpen className="h-6 w-6 text-slate-500" />}</div><div className="p-3.5"><div className="flex items-start justify-between gap-3"><p className="truncate text-sm font-medium text-slate-200">{asset.title}</p><span className="rounded bg-white/6 px-1.5 py-1 text-[10px] capitalize text-slate-400">{asset.type}</span></div><div className="mt-3 flex items-center gap-1.5 text-[10px]"><span className={`h-1.5 w-1.5 rounded-full ${asset.rightsStatus === "verified" ? "bg-emerald-300" : asset.rightsStatus === "review_required" ? "bg-amber-200" : "bg-slate-500"}`} /><span className="capitalize text-slate-500">{asset.rightsStatus.replace(/_/g, " ")}</span></div></div></article>) : <div className="col-span-full grid min-h-80 place-items-center text-center"><div><FolderOpen className="mx-auto h-6 w-6 text-slate-600" /><p className="mt-3 text-sm text-slate-500">No assets match this library view.</p></div></div>}</div></CardContent></Card></main></div></div>;
}
