import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { PageHeader } from "@/components/PageHeader";
import { ProjectPicker } from "@/components/ProjectPicker";
import { trpc } from "@/lib/trpc";
import { Bot, CheckCircle2, Loader2, Send, ShieldCheck, Wrench } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";

export default function Copilot() { const [projectId, setProjectId] = useState<number | null>(null); const [command, setCommand] = useState("Turn this into 8 Shorts for TikTok and YouTube Shorts."); const list = trpc.copilot.list.useQuery({ projectId: projectId ?? 0 }, { enabled: Boolean(projectId) }); const execute = trpc.copilot.execute.useMutation(); const submit = async (event: FormEvent) => { event.preventDefault(); if (!projectId) return toast.error("Select a project first."); try { const action = await execute.mutateAsync({ projectId, command }); await list.refetch(); setCommand(""); toast.success(`Executable action queued: ${action.toolName.replace(/_/g, " ")}`); } catch (error) { toast.error(error instanceof Error ? error.message : "The Copilot could not queue an action."); } };
  return <div className="min-h-full bg-[#0b1020]"><PageHeader eyebrow="AI operations" title="Action-only Copilot" description="Give production commands. The Copilot returns an audited, server-side tool action—not conversational filler." />{projectId && list.isLoading && <div className="mx-auto max-w-[1400px] px-5 pt-5 md:px-8" role="status" aria-live="polite"><div className="flex items-center gap-2 rounded-xl border border-cyan-200/10 bg-cyan-300/5 px-3 py-2 text-xs text-cyan-100"><Loader2 className="h-3.5 w-3.5 animate-spin" />Loading executable action log…</div></div>}
    <div className="mx-auto grid max-w-[1400px] gap-6 p-5 lg:grid-cols-[420px_1fr] md:p-8"><aside className="space-y-4"><Card className="border-cyan-300/16 bg-[linear-gradient(145deg,rgba(34,211,238,.08),rgba(124,58,237,.1))] shadow-none"><CardContent className="p-5"><div className="flex items-center gap-2 text-cyan-100"><Bot className="h-4 w-4" /><span className="text-xs font-semibold uppercase tracking-[.16em]">Command console</span></div><form className="mt-5 space-y-4" onSubmit={submit}><ProjectPicker projectId={projectId} onChange={setProjectId} /><Textarea value={command} onChange={e => setCommand(e.target.value)} placeholder="Turn this into 8 Shorts…" className="min-h-32 border-white/10 bg-slate-950/60 text-white placeholder:text-slate-600" /><Button disabled={!projectId || execute.isPending} className="w-full bg-cyan-300 text-slate-950 hover:bg-cyan-200">{execute.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Send className="mr-2 h-4 w-4" />}Execute as a tool action</Button></form></CardContent></Card><div className="rounded-2xl border border-white/7 bg-white/[.02] p-4 text-xs leading-5 text-slate-500"><ShieldCheck className="mb-2 h-4 w-4 text-emerald-300" />Publishing-plan actions always enter an approval-required state. The Copilot cannot bypass workspace roles, provider limits, or human approval.</div></aside>
      <main><Card className="border-white/7 bg-white/[.025] shadow-none"><CardContent className="p-0"><div className="border-b border-white/7 p-5"><h2 className="font-medium text-white">Executable action log</h2><p className="mt-1 text-xs text-slate-500">The exact tool and JSON parameters remain visible for review.</p></div><div className="divide-y divide-white/6">{list.data?.length ? list.data.map(action => <article className="p-5" key={action.id}><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-xl bg-violet-400/12"><Wrench className="h-4 w-4 text-violet-200" /></div><div><p className="text-sm font-medium text-slate-200">{action.toolName.replace(/_/g, " ")}</p><p className="mt-0.5 text-xs text-slate-500">Job #{action.jobId ?? "pending"}</p></div></div><span className={`rounded-full px-2.5 py-1 text-[10px] font-medium capitalize ${action.executionStatus === "awaiting_approval" ? "bg-amber-200/10 text-amber-100" : "bg-cyan-300/10 text-cyan-200"}`}>{action.executionStatus.replace(/_/g, " ")}</span></div><p className="mt-4 text-sm italic text-slate-400">“{action.command}”</p><pre className="mt-3 overflow-x-auto rounded-xl bg-slate-950/60 p-3 text-[11px] leading-5 text-cyan-100/80">{JSON.stringify(action.parameters, null, 2)}</pre></article>) : <div className="grid min-h-80 place-items-center text-center"><div><CheckCircle2 className="mx-auto h-6 w-6 text-slate-600" /><p className="mt-3 text-sm text-slate-500">No Copilot actions yet.</p><p className="mt-1 text-xs text-slate-600">Use a command to queue a traceable production action.</p></div></div>}</div></CardContent></Card></main></div></div>; }
