import { Card, CardContent } from "@/components/ui/card";
import { PageHeader } from "@/components/PageHeader";
import { CheckCircle2, CircleAlert, ShieldCheck } from "lucide-react";

export default function FoundationPage({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) {
  return <div className="min-h-full bg-[#0b1020]"><PageHeader eyebrow={eyebrow} title={title} description={description} />
    <div className="mx-auto max-w-5xl p-5 md:p-8"><Card className="overflow-hidden border-white/8 bg-white/[.03] shadow-none"><CardContent className="grid gap-0 p-0 md:grid-cols-[1.15fr_.85fr]"><div className="p-7 md:p-9"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-cyan-300/10"><ShieldCheck className="h-6 w-6 text-cyan-200" /></div><h2 className="mt-5 text-2xl font-semibold tracking-[-.035em] text-white">Production-safe foundation in place</h2><p className="mt-3 max-w-xl text-sm leading-7 text-slate-400">{description} This screen intentionally does not invent account connections, schedule success, analytics, or publication status. Those values appear only after an approved official integration supplies them.</p></div><div className="border-t border-white/8 bg-slate-950/30 p-7 md:border-l md:border-t-0"><p className="text-xs font-semibold uppercase tracking-[.16em] text-slate-500">Integration readiness</p><div className="mt-5 space-y-4"><div className="flex gap-3"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-emerald-300" /><div><p className="text-sm font-medium text-slate-200">Tenant-scoped data model</p><p className="mt-1 text-xs leading-5 text-slate-500">Projects, assets, jobs, approvals, and social records are isolated by workspace.</p></div></div><div className="flex gap-3"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-emerald-300" /><div><p className="text-sm font-medium text-slate-200">Official adapter boundary</p><p className="mt-1 text-xs leading-5 text-slate-500">Provider-specific OAuth and API logic remain outside the core product model.</p></div></div><div className="flex gap-3"><CircleAlert className="mt-0.5 h-4 w-4 shrink-0 text-amber-200" /><div><p className="text-sm font-medium text-slate-200">External credentials required</p><p className="mt-1 text-xs leading-5 text-slate-500">Connect approved accounts and service credentials before the corresponding action can execute.</p></div></div></div></div></CardContent></Card></div>
  </div>;
}
