import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { PageHeader } from "@/components/PageHeader";
import { useWorkspace } from "@/hooks/useWorkspace";
import { trpc } from "@/lib/trpc";
import { CircleX, Loader2, RotateCw, Sparkles } from "lucide-react";
import { toast } from "sonner";

const tone: Record<string, string> = { queued: "text-slate-300 bg-slate-300/10", processing: "text-cyan-200 bg-cyan-300/10", retrying: "text-amber-100 bg-amber-200/10", completed: "text-emerald-200 bg-emerald-300/10", failed: "text-rose-200 bg-rose-300/10", cancelled: "text-slate-400 bg-slate-500/10" };
export default function Jobs() { const { activeWorkspaceId } = useWorkspace(); const query = trpc.production.jobs.list.useQuery({ workspaceId: activeWorkspaceId ?? 0 }, { enabled: Boolean(activeWorkspaceId), refetchInterval: 4000 }); const utils = trpc.useUtils(); const cancel = trpc.production.jobs.cancel.useMutation(); const retry = trpc.production.jobs.retry.useMutation(); const perform = async (action: "cancel" | "retry", jobId: number) => { try { if (action === "cancel") await cancel.mutateAsync({ jobId }); else await retry.mutateAsync({ jobId }); await utils.production.jobs.list.invalidate({ workspaceId: activeWorkspaceId ?? 0 }); toast.success(action === "cancel" ? "Job cancellation requested." : "Job requeued."); } catch (error) { toast.error(error instanceof Error ? error.message : "Job action failed."); } };
  return <div className="min-h-full bg-[#0b1020]"><PageHeader eyebrow="Operations" title="Background jobs" description="Production jobs report progress, retain recoverable failure context, and can be cancelled or retried by authorized workspace members." />
    <div className="mx-auto max-w-6xl p-5 md:p-8"><Card className="border-white/7 bg-white/[.025] shadow-none"><CardContent className="p-0"><div className="flex items-center justify-between border-b border-white/7 p-5"><div><h2 className="font-medium text-white">Execution history</h2><p className="mt-1 text-xs text-slate-500">Auto-refreshes while jobs are processing.</p></div>{query.isFetching && <Loader2 className="h-4 w-4 animate-spin text-cyan-200" />}</div><div className="divide-y divide-white/6">{query.data?.length ? query.data.map(job => <div className="grid gap-4 p-5 md:grid-cols-[1fr_180px_120px]"><div><div className="flex items-center gap-2"><Sparkles className="h-3.5 w-3.5 text-cyan-200" /><p className="text-sm font-medium capitalize text-slate-200">{job.type.replace(/_/g, " ")}</p><span className={`rounded-full px-2 py-1 text-[10px] font-medium capitalize ${tone[job.status]}`}>{job.status}</span></div><p className="mt-2 text-xs text-slate-500">Job #{job.id}{job.errorMessage ? ` · ${job.errorMessage}` : " · Progress and output are retained with this production."}</p></div><div className="self-center"><div className="flex justify-between text-[10px] text-slate-500"><span>Progress</span><span>{job.progress}%</span></div><div className="mt-1.5 h-1.5 overflow-hidden rounded-full bg-white/7"><div className={`h-full rounded-full ${job.status === "failed" ? "bg-rose-300" : "bg-gradient-to-r from-violet-400 to-cyan-300"}`} style={{ width: `${job.progress}%` }} /></div></div><div className="flex items-center gap-2 md:justify-end">{["queued", "processing", "retrying"].includes(job.status) && <Button variant="outline" size="sm" onClick={() => perform("cancel", job.id)} className="border-white/10 bg-white/[.03] text-slate-300 hover:bg-rose-300/10 hover:text-rose-200"><CircleX className="mr-1.5 h-3.5 w-3.5" />Cancel</Button>}{job.status === "failed" && <Button size="sm" onClick={() => perform("retry", job.id)} className="bg-cyan-300 text-slate-950 hover:bg-cyan-200"><RotateCw className="mr-1.5 h-3.5 w-3.5" />Retry</Button>}</div></div>) : <div className="grid min-h-72 place-items-center text-center"><div><Sparkles className="mx-auto h-6 w-6 text-slate-600" /><p className="mt-3 text-sm text-slate-500">No jobs have been created in this workspace.</p></div></div>}</div></CardContent></Card></div></div>; }
