import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { PageHeader } from "@/components/PageHeader";
import { ProjectPicker } from "@/components/ProjectPicker";
import { trpc } from "@/lib/trpc";
import { BadgeCheck, BrainCircuit, FileSearch, Link2, Loader2, Plus } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";

export default function Research() {
  const [projectId, setProjectId] = useState<number | null>(null); const [title, setTitle] = useState(""); const [url, setUrl] = useState(""); const [excerpt, setExcerpt] = useState(""); const [sourceType, setSourceType] = useState<"user_provided" | "verified" | "ai_generated">("user_provided");
  const query = trpc.production.research.list.useQuery({ projectId: projectId ?? 0 }, { enabled: Boolean(projectId) }); const addSource = trpc.production.research.addSource.useMutation(); const extractClaims = trpc.production.research.extractClaims.useMutation();
  const add = async (event: FormEvent) => { event.preventDefault(); if (!projectId) return toast.error("Select a project first."); try { await addSource.mutateAsync({ projectId, title, url: url || undefined, excerpt, sourceType }); setTitle(""); setUrl(""); setExcerpt(""); await query.refetch(); toast.success("Source added with provenance." ); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not add source."); } };
  const extract = async () => { if (!projectId) return; try { await extractClaims.mutateAsync({ projectId }); await query.refetch(); toast.success("Claims extracted and labelled."); } catch (error) { toast.error(error instanceof Error ? error.message : "Claim extraction failed."); } };
  return <div className="min-h-full bg-[#0b1020]"><PageHeader eyebrow="Pre-production" title="Research workspace" description="Keep evidence, editorial suggestions, and user-provided notes visibly distinct at every step." />
    <div className="mx-auto grid max-w-[1600px] gap-6 p-5 lg:grid-cols-[360px_1fr] md:p-8"><aside><Card className="border-white/7 bg-white/[.035] shadow-none"><CardContent className="p-5"><ProjectPicker projectId={projectId} onChange={setProjectId} /><form onSubmit={add} className="mt-5 space-y-4"><label className="block"><span className="mb-1.5 block text-xs text-slate-400">Source title</span><Input required value={title} onChange={e => setTitle(e.target.value)} placeholder="Source or reference title" className="border-white/10 bg-slate-950/60 text-white placeholder:text-slate-600" /></label><label className="block"><span className="mb-1.5 block text-xs text-slate-400">URL (optional)</span><Input type="url" value={url} onChange={e => setUrl(e.target.value)} placeholder="https://…" className="border-white/10 bg-slate-950/60 text-white placeholder:text-slate-600" /></label><label className="block"><span className="mb-1.5 block text-xs text-slate-400">Evidence or note</span><Textarea required value={excerpt} onChange={e => setExcerpt(e.target.value)} placeholder="Paste the relevant, rights-cleared text or your production note…" className="min-h-32 border-white/10 bg-slate-950/60 text-white placeholder:text-slate-600" /></label><label className="block"><span className="mb-1.5 block text-xs text-slate-400">Information status</span><select value={sourceType} onChange={e => setSourceType(e.target.value as typeof sourceType)} className="h-10 w-full rounded-lg border border-white/10 bg-slate-950/60 px-3 text-sm text-white outline-none"><option value="user_provided">User-provided</option><option value="verified">Verified source</option><option value="ai_generated">AI-generated note</option></select></label><Button disabled={addSource.isPending || !projectId} className="w-full bg-cyan-300 text-slate-950 hover:bg-cyan-200"><Plus className="mr-2 h-4 w-4" />Add source</Button></form></CardContent></Card></aside>
    <main className="space-y-5">{projectId && query.isLoading && <p role="status" className="text-xs text-cyan-100">Loading source material…</p>}<Card className="border-cyan-300/12 bg-cyan-300/[.045] shadow-none"><CardContent className="flex flex-col justify-between gap-4 p-5 md:flex-row md:items-center"><div><p className="text-sm font-medium text-cyan-100">Source-grounded extraction</p><p className="mt-1 text-xs leading-5 text-slate-400">Verified claims remain attached to their source. AI editorial synthesis is marked separately and never presented as verified.</p></div><Button disabled={extractClaims.isPending || !projectId || !query.data?.sources.length} onClick={extract} variant="outline" className="border-cyan-200/20 bg-cyan-300/8 text-cyan-100 hover:bg-cyan-300/15">{extractClaims.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <FileSearch className="mr-2 h-4 w-4" />}Extract claims</Button></CardContent></Card>
      <div className="grid gap-5 xl:grid-cols-2">{query.data?.summary && <Card className="border-cyan-300/12 bg-cyan-300/[.045] shadow-none xl:col-span-2"><CardContent className="p-5"><div className="flex items-start gap-3"><div className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-cyan-300/12 text-cyan-100"><FileSearch className="h-4 w-4" /></div><div><p className="text-sm font-medium text-cyan-100">Source-grounded editorial summary</p><p className="mt-2 max-w-4xl text-sm leading-6 text-slate-300">{query.data.summary.summary}</p><div className="mt-3 flex flex-wrap gap-2 text-[10px] uppercase tracking-wide text-slate-500"><span>{query.data.summary.sourceCount} sources</span><span>·</span><span>{query.data.summary.verifiedClaimCount} verified claims</span><span>·</span><span>{query.data.summary.synthesisClaimCount} editorial syntheses</span></div></div></div></CardContent></Card>}<Card className="border-white/7 bg-white/[.025] shadow-none"><CardContent className="p-0"><div className="border-b border-white/7 p-5"><h2 className="font-medium text-white">Sources</h2><p className="mt-1 text-xs text-slate-500">Evidence available to this project.</p></div><div className="divide-y divide-white/6">{query.data?.sources.length ? query.data.sources.map(source => <div className="p-5" key={source.id}><div className="flex items-start justify-between gap-3"><p className="text-sm font-medium text-slate-200">{source.title}</p><span className={`rounded-full px-2 py-1 text-[10px] font-medium uppercase tracking-wide ${source.sourceType === "verified" ? "bg-emerald-300/12 text-emerald-200" : source.sourceType === "ai_generated" ? "bg-violet-300/12 text-violet-200" : "bg-slate-300/10 text-slate-300"}`}>{source.sourceType.replace("_", " ")}</span></div><p className="mt-2 line-clamp-4 text-xs leading-5 text-slate-500">{source.excerpt}</p>{source.url && <a href={source.url} target="_blank" rel="noreferrer" className="mt-3 inline-flex items-center text-xs text-cyan-200 hover:text-cyan-100"><Link2 className="mr-1 h-3 w-3" />Open reference</a>}</div>) : <Empty icon={Link2} text="No source material yet." />}</div></CardContent></Card>
      <Card className="border-white/7 bg-white/[.025] shadow-none"><CardContent className="p-0"><div className="border-b border-white/7 p-5"><h2 className="font-medium text-white">Claims and notes</h2><p className="mt-1 text-xs text-slate-500">Every item retains an explicit information label.</p></div><div className="divide-y divide-white/6">{query.data?.claims.length ? query.data.claims.map(claim => { const citation = query.data.citations.find(item => item.claimId === claim.id); return <div className="p-5" key={claim.id}><div className="flex gap-3"><div className={`mt-0.5 grid h-7 w-7 shrink-0 place-items-center rounded-lg ${claim.classification === "verified" ? "bg-emerald-300/12 text-emerald-200" : "bg-violet-300/12 text-violet-200"}`}>{claim.classification === "verified" ? <BadgeCheck className="h-4 w-4" /> : <BrainCircuit className="h-4 w-4" />}</div><div><p className="text-sm leading-6 text-slate-200">{claim.text}</p><p className="mt-2 text-[10px] font-semibold uppercase tracking-[.14em] text-slate-500">{claim.classification === "verified" ? "Verified by linked source" : "AI-generated editorial synthesis"}</p>{citation && <div className="mt-3 rounded-lg border border-emerald-300/10 bg-emerald-300/[.04] p-3"><p className="text-[10px] font-semibold uppercase tracking-[.12em] text-emerald-200">Citation excerpt</p><p className="mt-1 text-xs leading-5 text-slate-400">“{citation.quote}”</p>{citation.locator && <p className="mt-1 truncate text-[10px] text-cyan-200">{citation.locator}</p>}</div>}</div></div></div>; }) : <Empty icon={BrainCircuit} text="Add source material, then extract traceable claims." />}</div></CardContent></Card></div></main></div></div>;
}
function Empty({ icon: Icon, text }: { icon: typeof Link2; text: string }) { return <div className="grid min-h-56 place-items-center p-6 text-center"><div><Icon className="mx-auto h-5 w-5 text-slate-600" /><p className="mt-3 text-xs text-slate-500">{text}</p></div></div>; }
