import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { PageHeader } from "@/components/PageHeader";
import { ProjectPicker } from "@/components/ProjectPicker";
import { trpc } from "@/lib/trpc";
import { BookOpenText, ChevronRight, Loader2, Sparkles, Wand2 } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { toast } from "sonner";

type Scene = { id: string; duration: number; voiceover: string; visualPrompt: string; broll: string; onscreenText: string; transition: string; music: string; soundEffect: string };
type ScriptContent = { title: string; language: string; hook: string; summary: string; cta: string; scenes: Scene[] };

export default function ScriptStudio() {
  const [projectId, setProjectId] = useState<number | null>(null);
  const [topic, setTopic] = useState(""); const [audience, setAudience] = useState("Business leaders and security teams"); const [tone, setTone] = useState("Clear, authoritative, and cinematic"); const [language, setLanguage] = useState<"en" | "fr">("en"); const [durationMinutes, setDurationMinutes] = useState(5); const [keywords, setKeywords] = useState("");
  useEffect(() => { const value = new URLSearchParams(window.location.search).get("project"); if (value) setProjectId(Number(value)); }, []);
  const { data: savedScript, refetch } = trpc.production.script.get.useQuery({ projectId: projectId ?? 0 }, { enabled: Boolean(projectId) });
  const generate = trpc.production.script.generate.useMutation();
  const content = (savedScript?.[0]?.content as ScriptContent | undefined) ?? null;
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!projectId) return toast.error("Select a project first."); try { await generate.mutateAsync({ projectId, topic, audience, language, tone, durationMinutes, keywords: keywords.split(",").map(item => item.trim()).filter(Boolean) }); await refetch(); toast.success("Structured script is ready for review."); } catch (error) { toast.error(error instanceof Error ? error.message : "Script generation failed."); } };
  return <div className="min-h-full bg-[#0b1020]"><PageHeader eyebrow="Pre-production" title="Script Studio" description="Turn a clear production brief into an editable scene plan with every creative cue structured for downstream work." />
    <div className="mx-auto grid max-w-[1600px] gap-6 p-5 md:grid-cols-[360px_1fr] md:p-8"><aside className="space-y-4"><Card className="border-white/7 bg-white/[.035] shadow-none"><CardContent className="p-5"><div className="mb-5 flex items-center gap-2 text-cyan-200"><Wand2 className="h-4 w-4" /><span className="text-xs font-semibold uppercase tracking-[.15em]">Production brief</span></div><form onSubmit={submit} className="space-y-4"><ProjectPicker projectId={projectId} onChange={setProjectId} /><label className="block"><span className="mb-1.5 block text-xs font-medium text-slate-400">Topic</span><Textarea value={topic} onChange={e => setTopic(e.target.value)} required placeholder="How AI is changing cybersecurity" className="min-h-24 border-white/10 bg-slate-950/60 text-white placeholder:text-slate-600" /></label><label className="block"><span className="mb-1.5 block text-xs font-medium text-slate-400">Audience</span><Input value={audience} onChange={e => setAudience(e.target.value)} className="border-white/10 bg-slate-950/60 text-white" /></label><div className="grid grid-cols-2 gap-3"><label><span className="mb-1.5 block text-xs font-medium text-slate-400">Language</span><select value={language} onChange={e => setLanguage(e.target.value as "en" | "fr")} className="h-10 w-full rounded-lg border border-white/10 bg-slate-950/60 px-3 text-sm text-white outline-none"><option value="en">English</option><option value="fr">Français</option></select></label><label><span className="mb-1.5 block text-xs font-medium text-slate-400">Minutes</span><Input type="number" min={1} max={60} value={durationMinutes} onChange={e => setDurationMinutes(Number(e.target.value))} className="border-white/10 bg-slate-950/60 text-white" /></label></div><label className="block"><span className="mb-1.5 block text-xs font-medium text-slate-400">Voice and tone</span><Input value={tone} onChange={e => setTone(e.target.value)} className="border-white/10 bg-slate-950/60 text-white" /></label><label className="block"><span className="mb-1.5 block text-xs font-medium text-slate-400">Keywords</span><Input value={keywords} onChange={e => setKeywords(e.target.value)} placeholder="AI, security, resilience" className="border-white/10 bg-slate-950/60 text-white placeholder:text-slate-600" /></label><Button disabled={generate.isPending || !projectId} className="w-full bg-cyan-300 text-slate-950 hover:bg-cyan-200">{generate.isPending ? <><Loader2 className="mr-2 h-4 w-4 animate-spin" />Building scene plan</> : <><Sparkles className="mr-2 h-4 w-4" />Generate structured script</>}</Button></form></CardContent></Card><p className="px-2 text-xs leading-5 text-slate-500">Generation produces structured JSON for the editor. It never treats unverified research as a source of fact.</p></aside>
      <main className="min-w-0"><Card className="min-h-[680px] border-white/7 bg-white/[.025] shadow-none"><CardContent className="p-0">{content ? <><div className="border-b border-white/7 p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2"><span className="rounded-full bg-violet-400/15 px-2.5 py-1 text-[11px] font-medium uppercase tracking-wider text-violet-200">Structured JSON</span><span className="text-xs text-slate-500">{content.language.toUpperCase()} · {content.scenes.length} scenes</span></div><h2 className="mt-3 text-2xl font-semibold tracking-[-.035em] text-white">{content.title}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">{content.summary}</p></div></div><div className="mt-6 rounded-2xl border border-cyan-200/10 bg-cyan-300/[.045] p-4"><p className="text-[11px] font-semibold uppercase tracking-[.15em] text-cyan-200">Opening hook</p><p className="mt-2 text-base font-medium leading-7 text-slate-100">“{content.hook}”</p></div></div><div className="divide-y divide-white/6">{content.scenes.map((scene, index) => <article className="grid gap-4 p-5 md:grid-cols-[72px_1fr_250px]" key={scene.id}><div><p className="text-xs font-semibold text-cyan-200">{String(index + 1).padStart(2, "0")}</p><p className="mt-1 text-xs text-slate-500">{scene.duration}s</p></div><div><p className="text-sm font-medium leading-6 text-white">{scene.voiceover}</p><p className="mt-3 text-xs leading-5 text-slate-500">On screen: <span className="text-slate-300">{scene.onscreenText || "No on-screen text"}</span></p></div><div className="rounded-xl border border-white/7 bg-slate-950/35 p-3 text-xs"><p className="font-medium text-slate-300">Visual direction</p><p className="mt-1.5 leading-5 text-slate-500">{scene.visualPrompt}</p><p className="mt-3 text-slate-500">B-roll: <span className="text-slate-400">{scene.broll}</span></p><div className="mt-3 flex flex-wrap gap-1.5"><span className="rounded bg-white/6 px-1.5 py-1 text-slate-400">{scene.transition}</span><span className="rounded bg-white/6 px-1.5 py-1 text-slate-400">{scene.soundEffect}</span></div></div></article>)}</div><div className="border-t border-white/7 p-5"><p className="text-xs font-semibold uppercase tracking-[.15em] text-slate-500">Call to action</p><p className="mt-2 text-sm text-slate-200">{content.cta}</p></div></> : <div className="grid min-h-[680px] place-items-center p-8 text-center"><div><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-violet-400/10"><BookOpenText className="h-6 w-6 text-violet-200" /></div><h2 className="mt-5 text-lg font-medium text-white">Your scene plan will appear here</h2><p className="mx-auto mt-2 max-w-sm text-sm leading-6 text-slate-500">Select a project, add a focused brief, and generate a structured script that remains editable at every production stage.</p></div></div>}</CardContent></Card></main>
    </div></div>;
}
