import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { PageHeader } from "@/components/PageHeader";
import { ProjectPicker } from "@/components/ProjectPicker";
import { useWorkspace } from "@/hooks/useWorkspace";
import { trpc } from "@/lib/trpc";
import { Captions, FileAudio, Loader2, Mic2, SlidersHorizontal } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";

export default function VoiceCaptions() {
  const { activeWorkspaceId } = useWorkspace(); const [projectId, setProjectId] = useState<number | null>(null); const [audioUrl, setAudioUrl] = useState(""); const [language, setLanguage] = useState<"en" | "fr">("en"); const [result, setResult] = useState<{ transcript: string; srt: string; vtt: string } | null>(null);
  const voices = trpc.production.voice.list.useQuery({ workspaceId: activeWorkspaceId ?? 0, language }, { enabled: Boolean(activeWorkspaceId) }); const transcribe = trpc.production.voice.transcribe.useMutation();
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!projectId) return toast.error("Select a project first."); try { const value = await transcribe.mutateAsync({ projectId, audioUrl, language, title: "Project transcript" }); setResult(value); toast.success("Transcript and subtitle files are ready."); } catch (error) { toast.error(error instanceof Error ? error.message : "Transcription failed."); } };
  const download = (name: string, value: string, type: string) => { const url = URL.createObjectURL(new Blob([value], { type })); const link = document.createElement("a"); link.href = url; link.download = name; link.click(); URL.revokeObjectURL(url); };
  return <div className="min-h-full bg-[#0b1020]"><PageHeader eyebrow="Voice & accessibility" title="Voice and captions" description="Select permitted voices, transcribe source audio, and export word-timed subtitles for production and publishing." />
    <div className="mx-auto grid max-w-[1600px] gap-6 p-5 lg:grid-cols-[360px_1fr] md:p-8"><aside className="space-y-4"><Card className="border-white/7 bg-white/[.035] shadow-none"><CardContent className="p-5"><div className="flex items-center gap-2 text-cyan-200"><FileAudio className="h-4 w-4" /><span className="text-xs font-semibold uppercase tracking-[.15em]">Transcription</span></div><form className="mt-5 space-y-4" onSubmit={submit}><ProjectPicker projectId={projectId} onChange={setProjectId} /><label className="block"><span className="mb-1.5 block text-xs text-slate-400">Audio URL</span><Input required type="url" value={audioUrl} onChange={e => setAudioUrl(e.target.value)} placeholder="https://…/source-audio.mp3" className="border-white/10 bg-slate-950/60 text-white placeholder:text-slate-600" /></label><label className="block"><span className="mb-1.5 block text-xs text-slate-400">Spoken language</span><select value={language} onChange={e => setLanguage(e.target.value as "en" | "fr")} className="h-10 w-full rounded-lg border border-white/10 bg-slate-950/60 px-3 text-sm text-white outline-none"><option value="en">English</option><option value="fr">Français</option></select></label><Button disabled={!projectId || transcribe.isPending} className="w-full bg-cyan-300 text-slate-950 hover:bg-cyan-200">{transcribe.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Captions className="mr-2 h-4 w-4" />}Transcribe and generate subtitles</Button></form></CardContent></Card><p className="px-2 text-xs leading-5 text-slate-500">The transcription service accepts pre-uploaded audio URLs. Media records and object storage are tenant-scoped in the platform model.</p></aside>
    <main className="space-y-5"><Card className="border-white/7 bg-white/[.025] shadow-none"><CardContent className="p-0"><div className="flex items-center justify-between border-b border-white/7 p-5"><div><h2 className="font-medium text-white">Voice catalog</h2><p className="mt-1 text-xs text-slate-500">Filterable provider registry for permitted workspace voices.</p></div><SlidersHorizontal className="h-4 w-4 text-slate-500" /></div>{voices.data?.length ? <div className="grid gap-3 p-5 sm:grid-cols-2 xl:grid-cols-3">{voices.data.map(voice => <div className="rounded-xl border border-white/7 bg-slate-950/35 p-4" key={voice.id}><div className="flex items-center gap-2"><div className="grid h-8 w-8 place-items-center rounded-lg bg-violet-400/12"><Mic2 className="h-4 w-4 text-violet-200" /></div><div><p className="text-sm font-medium text-slate-200">{voice.name}</p><p className="text-[10px] uppercase tracking-wide text-slate-500">{voice.language} · {voice.gender}</p></div></div><p className="mt-4 text-xs text-slate-500">{voice.tone || "No tone profile"} · {voice.accent || "Unspecified accent"}</p><span className={`mt-3 inline-block rounded px-1.5 py-1 text-[10px] ${voice.commercialUse === "allowed" ? "bg-emerald-300/10 text-emerald-200" : "bg-amber-200/10 text-amber-100"}`}>{voice.commercialUse === "allowed" ? "Commercial use allowed" : "License review required"}</span></div>)}</div> : <div className="grid min-h-52 place-items-center text-center"><div><Mic2 className="mx-auto h-5 w-5 text-slate-600" /><p className="mt-3 text-sm text-slate-500">No voices have been approved for this workspace.</p><p className="mt-1 text-xs text-slate-600">Add provider-backed voices through the administrative registry before use.</p></div></div>}</CardContent></Card>
      <Card className="border-white/7 bg-white/[.025] shadow-none"><CardContent className="p-0"><div className="border-b border-white/7 p-5"><h2 className="font-medium text-white">Caption review</h2><p className="mt-1 text-xs text-slate-500">Word-level timing is preserved with the transcript for animated caption styling.</p></div>{result ? <div className="p-5"><p className="whitespace-pre-wrap text-sm leading-7 text-slate-300">{result.transcript}</p><div className="mt-6 flex flex-wrap gap-3"><Button variant="outline" className="border-white/10 bg-white/[.035] text-slate-200 hover:bg-white/10" onClick={() => download("captions.srt", result.srt, "application/x-subrip")}>Download SRT</Button><Button variant="outline" className="border-white/10 bg-white/[.035] text-slate-200 hover:bg-white/10" onClick={() => download("captions.vtt", result.vtt, "text/vtt")}>Download VTT</Button></div></div> : <div className="grid min-h-48 place-items-center text-center"><div><Captions className="mx-auto h-5 w-5 text-slate-600" /><p className="mt-3 text-sm text-slate-500">Your transcript and exports will appear here.</p></div></div>}</CardContent></Card></main></div></div>;
}
