import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { PageHeader } from "@/components/PageHeader";
import { useWorkspace } from "@/hooks/useWorkspace";
import { trpc } from "@/lib/trpc";
import { Building2, Loader2, Plus, ShieldCheck, UsersRound } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";

export default function Workspace() { const context = useWorkspace(); const [organizationName, setOrganizationName] = useState(""); const [workspaceName, setWorkspaceName] = useState(""); const [kind, setKind] = useState<"studio" | "agency" | "client">("agency"); const create = trpc.workspace.create.useMutation(); const members = trpc.workspace.members.useQuery({ workspaceId: context.activeWorkspaceId ?? 0 }, { enabled: Boolean(context.activeWorkspaceId) }); const submit = async (event: FormEvent) => { event.preventDefault(); try { const result = await create.mutateAsync({ organizationName, workspaceName, kind }); await context.refetch(); context.selectWorkspace(result.workspaceId); setOrganizationName(""); setWorkspaceName(""); toast.success("Workspace created and isolated."); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not create workspace."); } };
  return <div className="min-h-full bg-[#0b1020]"><PageHeader eyebrow="Governance" title="Workspaces and client separation" description="Maintain agency, client, and studio boundaries with explicit memberships and scoped roles." />
    <div className="mx-auto grid max-w-[1400px] gap-6 p-5 lg:grid-cols-[.85fr_1.15fr] md:p-8"><aside><Card className="border-white/7 bg-white/[.035] shadow-none"><CardContent className="p-5"><div className="flex items-center gap-2 text-cyan-200"><Building2 className="h-4 w-4" /><span className="text-xs font-semibold uppercase tracking-[.15em]">New workspace</span></div><form className="mt-5 space-y-4" onSubmit={submit}><label className="block"><span className="mb-1.5 block text-xs text-slate-400">Organization</span><Input required value={organizationName} onChange={e => setOrganizationName(e.target.value)} placeholder="Northstar Creative" className="border-white/10 bg-slate-950/60 text-white placeholder:text-slate-600" /></label><label className="block"><span className="mb-1.5 block text-xs text-slate-400">Workspace</span><Input required value={workspaceName} onChange={e => setWorkspaceName(e.target.value)} placeholder="Northstar Client Team" className="border-white/10 bg-slate-950/60 text-white placeholder:text-slate-600" /></label><label className="block"><span className="mb-1.5 block text-xs text-slate-400">Boundary</span><select value={kind} onChange={e => setKind(e.target.value as typeof kind)} className="h-10 w-full rounded-lg border border-white/10 bg-slate-950/60 px-3 text-sm text-white outline-none"><option value="studio">Studio</option><option value="agency">Agency</option><option value="client">Client workspace</option></select></label><Button disabled={create.isPending} className="w-full bg-cyan-300 text-slate-950 hover:bg-cyan-200">{create.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Plus className="mr-2 h-4 w-4" />}Create isolated workspace</Button></form></CardContent></Card></aside>
      <main className="space-y-5"><Card className="border-white/7 bg-white/[.025] shadow-none"><CardContent className="p-0"><div className="border-b border-white/7 p-5"><h2 className="font-medium text-white">Available workspaces</h2><p className="mt-1 text-xs text-slate-500">Switching changes the tenant context used for every project, asset, job, and action.</p></div><div className="divide-y divide-white/6">{context.data?.workspaces.map(item => <button onClick={() => context.selectWorkspace(item.workspace.id)} className="flex w-full items-center gap-4 p-5 text-left hover:bg-white/[.03]" key={item.workspace.id}><div className="grid h-10 w-10 place-items-center rounded-xl bg-violet-400/12"><Building2 className="h-4 w-4 text-violet-200" /></div><div className="flex-1"><p className="text-sm font-medium text-slate-200">{item.workspace.name}</p><p className="mt-1 text-xs text-slate-500">{item.organization.name} · {item.organization.kind} · {item.membership.role}</p></div>{context.activeWorkspaceId === item.workspace.id && <span className="rounded-full bg-cyan-300/10 px-2.5 py-1 text-[10px] font-medium text-cyan-200">Active</span>}</button>)}</div></CardContent></Card><Card className="border-white/7 bg-white/[.025] shadow-none"><CardContent className="p-0"><div className="border-b border-white/7 p-5"><h2 className="font-medium text-white">Current membership scope</h2><p className="mt-1 text-xs text-slate-500">Role changes require owner or administrator authorization.</p></div><div className="divide-y divide-white/6">{members.data?.length ? members.data.map(member => <div className="flex items-center gap-3 p-5" key={member.id}><div className="grid h-9 w-9 place-items-center rounded-xl bg-white/[.05]"><UsersRound className="h-4 w-4 text-slate-400" /></div><div className="flex-1"><p className="text-sm text-slate-200">Workspace member #{member.userId}</p><p className="mt-1 text-xs text-slate-500">Role: {member.role} · {member.status}</p></div><ShieldCheck className="h-4 w-4 text-emerald-300" /></div>) : <div className="p-8 text-center text-sm text-slate-500">Select a workspace to view membership scope.</div>}</div></CardContent></Card></main></div></div>; }
